/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.example.gui;

import com.example.domain.Historico;
import com.example.domain.ObjetoExp;
import com.example.domain.ObraArte;
import com.example.services.GestorSala;
import java.io.FileOutputStream;
import javax.swing.JOptionPane;

/**
 *
 * @author MARTIN
 */
public class JDNuevoObjeto extends javax.swing.JDialog {

    /**
     * Creates new form JDNuevoObjeto
     */
    private GestorSala gestor;
    private String salaSeleccionada;

    public JDNuevoObjeto(java.awt.Frame parent, boolean modal, GestorSala gestor, String sala) {
        super(parent, modal);
        this.gestor = gestor;
        this.salaSeleccionada = sala;
        initComponents();
        jlbSala.setText("Sala: " + salaSeleccionada);
        jcbTipos.setSelectedIndex(0);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jcbTipos = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jtNombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jtCodigo = new javax.swing.JTextField();
        jtAnio = new javax.swing.JTextField();
        jlbAnio = new javax.swing.JLabel();
        lblExtra1 = new javax.swing.JLabel();
        jtExtra = new javax.swing.JTextField();
        jlbExtra2 = new javax.swing.JLabel();
        jtExtra2 = new javax.swing.JTextField();
        jbAceptar = new javax.swing.JButton();
        jbCancelar = new javax.swing.JButton();
        jlbSala = new javax.swing.JLabel();
        jlbCampo1 = new javax.swing.JLabel();
        jlbCampo2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Agregar nuevo objeto");
        setResizable(false);

        jLabel3.setText("Tipo objeto:");

        jcbTipos.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1-Objeto Histórico", "2-Obra Arte" }));
        jcbTipos.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcbTiposItemStateChanged(evt);
            }
        });
        jcbTipos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbTiposActionPerformed(evt);
            }
        });

        jLabel1.setText("Nombre:");

        jLabel2.setText("Código:");

        jtCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtCodigoActionPerformed(evt);
            }
        });

        jtAnio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtAnioActionPerformed(evt);
            }
        });

        jlbAnio.setText("Anio:");

        jtExtra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtExtraActionPerformed(evt);
            }
        });

        jtExtra2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtExtra2ActionPerformed(evt);
            }
        });

        jbAceptar.setText("Aceptar");
        jbAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAceptarActionPerformed(evt);
            }
        });

        jbCancelar.setText("Cancelar");
        jbCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCancelarActionPerformed(evt);
            }
        });

        jlbSala.setText("Sala:");

        jlbCampo1.setText("jLabel4");

        jlbCampo2.setText("jLabel5");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlbSala, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jlbAnio, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jlbCampo1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jlbCampo2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbAceptar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbCancelar))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jtExtra)
                        .addComponent(jtAnio)
                        .addComponent(jtNombre)
                        .addComponent(jcbTipos, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jtExtra2)
                        .addComponent(jtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jlbExtra2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblExtra1)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addComponent(lblExtra1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlbExtra2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(jlbSala)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jcbTipos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtAnio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlbAnio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtExtra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlbCampo1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtExtra2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlbCampo2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbAceptar)
                    .addComponent(jbCancelar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jcbTiposItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcbTiposItemStateChanged

    }//GEN-LAST:event_jcbTiposItemStateChanged

    private void jcbTiposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbTiposActionPerformed
        if (jcbTipos.getSelectedIndex() != -1) {
            char t = jcbTipos.getSelectedItem().toString().charAt(0);
            if (t == '1') {
                jlbCampo1.setText("Zona:");
                jlbCampo2.setText("Origen:");
            } else {
                jlbCampo1.setText("Autor:");
                jlbCampo2.setText("País:");
            }
        }
    }//GEN-LAST:event_jcbTiposActionPerformed

    private void jtCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtCodigoActionPerformed

    private void jtAnioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtAnioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtAnioActionPerformed

    private void jtExtraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtExtraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtExtraActionPerformed

    private void jtExtra2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtExtra2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtExtra2ActionPerformed

    private void jbAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAceptarActionPerformed
        String nom;
        int cod, anio;

        try {
            cod = Integer.parseInt(jtCodigo.getText());
            nom = jtNombre.getText();
            anio = Integer.parseInt(jtAnio.getText());

            ObjetoExp o;
            String campo1 = jtExtra.getText();
            String campo2 = jtExtra2.getText();

            if (jcbTipos.getSelectedItem().toString().charAt(0) == '1') {
                o = new Historico(campo1, campo2, cod, nom, anio);
            } else {
                o = new ObraArte(campo1, campo2, cod, nom, anio);
            }
            gestor.agregarObjeto(o, salaSeleccionada);
            this.dispose();
        } catch (NumberFormatException nfe) {
            JOptionPane.showMessageDialog(this, "Error de números");
        }finally{
            //Bloque que se ejecuta SIEMPRE...
            //independiente si se presentó o no un error en el 
            //catch.
        }
    }//GEN-LAST:event_jbAceptarActionPerformed

    private void jbCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_jbCancelarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton jbAceptar;
    private javax.swing.JButton jbCancelar;
    private javax.swing.JComboBox jcbTipos;
    private javax.swing.JLabel jlbAnio;
    private javax.swing.JLabel jlbCampo1;
    private javax.swing.JLabel jlbCampo2;
    private javax.swing.JLabel jlbExtra2;
    private javax.swing.JLabel jlbSala;
    private javax.swing.JTextField jtAnio;
    private javax.swing.JTextField jtCodigo;
    private javax.swing.JTextField jtExtra;
    private javax.swing.JTextField jtExtra2;
    private javax.swing.JTextField jtNombre;
    private javax.swing.JLabel lblExtra1;
    // End of variables declaration//GEN-END:variables
}
