/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.example.gui;

import com.example.domain.Historico;
import com.example.domain.ObjetoExp;
import com.example.domain.ObraArte;
import com.example.domain.Sala;
import com.example.services.GestorSala;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author MARTIN
 */
public class JFMuseo extends javax.swing.JFrame {

    /**
     * Creates new form JFMuseo
     */
    private GestorSala gestor;

    public JFMuseo() {
        initComponents();
        jbConsultar.addMouseListener(new EscuchaMouse());
        gestor = new GestorSala();
        DefaultComboBoxModel modelo = new DefaultComboBoxModel(gestor.getSalas());
        jcSalas.setModel(modelo);
        //abrir en el centro de la pantalla:
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jtObjetos = new javax.swing.JTable();
        jcSalas = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jbConsultar = new javax.swing.JButton();
        jlTotal = new javax.swing.JLabel();
        jbAgregar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Museo Rocksen");

        jtObjetos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nombre", "Año", "Zona", "Origen", "Autor", "País"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jtObjetos);

        jLabel1.setText("Sala:");

        jbConsultar.setText("Consultar");
        jbConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbConsultarActionPerformed(evt);
            }
        });

        jlTotal.setText("Total de objetos:");

        jbAgregar.setText("Agregar");
        jbAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAgregarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jlTotal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbAgregar))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jcSalas, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbConsultar)
                        .addGap(0, 142, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcSalas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jbConsultar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlTotal)
                    .addComponent(jbAgregar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAgregarActionPerformed

        if (jcSalas.getSelectedItem() != null) {
            new JDNuevoObjeto(this, true, gestor, jcSalas.getSelectedItem().toString()).setVisible(true);
        }
    }//GEN-LAST:event_jbAgregarActionPerformed

    private void jbConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbConsultarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbConsultarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbAgregar;
    private javax.swing.JButton jbConsultar;
    private javax.swing.JComboBox jcSalas;
    private javax.swing.JLabel jlTotal;
    private javax.swing.JTable jtObjetos;
    // End of variables declaration//GEN-END:variables

    class EscuchaMouse extends MouseAdapter {

        @Override
        public void mouseClicked(MouseEvent me) {

            String[] columnas = {"Código", "Nombre", "Año", "Zona", "Origen",
                "Autor", "País"};
            DefaultTableModel tabla = new DefaultTableModel();
            tabla.setColumnIdentifiers(columnas);

            Sala s = (Sala) jcSalas.getSelectedItem();
            if (s != null) {
                jlTotal.setText("Total de objetos:" + s.getTotalObjetos());

                String[] fila = new String[7];
                for (ObjetoExp obj : s.getObjetos()) {
                    fila[0] = String.valueOf(obj.getCod());
                    fila[1] = obj.getNombre();
                    fila[2] = String.valueOf(obj.getAnio());

                    if (obj instanceof Historico) {
                        Historico h = (Historico) obj;
                        fila[3] = h.getZona();
                        fila[4] = h.getOrigen();
                        fila[5] = "";
                        fila[6] = "";
                    } else {
                        ObraArte o = (ObraArte) obj;
                        fila[3] = "";
                        fila[4] = "";
                        fila[5] = o.getAutor();
                        fila[6] = o.getPais();
                    }
                    tabla.addRow(fila);
                }
                jtObjetos.setModel(tabla);
            }
        }
    }
}
