/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ejemplo.gui;

import com.ejemplo.dominio.Bidon;
import com.ejemplo.dominio.Caja;
import com.ejemplo.dominio.Camion;
import com.ejemplo.dominio.Carga;
import com.ejemplo.dominio.Packing;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author MARTIN
 */
public class JFPrincipal extends javax.swing.JFrame {

    private Camion camion;

    /**
     * Creates new form JFPrincipal
     */
    public JFPrincipal() {
        super();
        camion = new Camion(10000);
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jtCargas = new javax.swing.JTable();
        jbSubir = new javax.swing.JButton();
        jbBajar = new javax.swing.JButton();
        jcEstados = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jbAsignar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jtCantidadCargas = new javax.swing.JTextField();
        jbSalir = new javax.swing.JButton();
        jbValidarDisponibilidad = new javax.swing.JButton();
        jtPesoTotal = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jcMostrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Carga de camión");
        setResizable(false);

        jtCargas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Contenido", "Peso", "Densidad", "Capacidad", "Cantidad Cajas", "Peso x Caja", "Peso Estructura"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtCargas.setColumnSelectionAllowed(true);
        jtCargas.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(jtCargas);
        jtCargas.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (jtCargas.getColumnModel().getColumnCount() > 0) {
            jtCargas.getColumnModel().getColumn(1).setResizable(false);
            jtCargas.getColumnModel().getColumn(2).setResizable(false);
            jtCargas.getColumnModel().getColumn(3).setResizable(false);
            jtCargas.getColumnModel().getColumn(4).setResizable(false);
            jtCargas.getColumnModel().getColumn(5).setResizable(false);
            jtCargas.getColumnModel().getColumn(6).setResizable(false);
        }

        jbSubir.setText("Subir Carga");
        jbSubir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSubirActionPerformed(evt);
            }
        });

        jbBajar.setText("Bajar Carga");
        jbBajar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBajarActionPerformed(evt);
            }
        });

        jcEstados.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1- Disponible", "2- En Viaje", "3- En Reparación" }));

        jLabel1.setText("Estado camión:");

        jbAsignar.setText("Asignar");

        jLabel2.setText("Total de cargas:");

        jtCantidadCargas.setEnabled(false);

        jbSalir.setText("Salir");
        jbSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalirActionPerformed(evt);
            }
        });

        jbValidarDisponibilidad.setText("Validar Disponibilidad");

        jtPesoTotal.setEnabled(false);

        jLabel3.setText("Peso total:");

        jcMostrar.setText("MostrarCargas");
        jcMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcMostrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jcEstados, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbAsignar, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtCantidadCargas, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtPesoTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jbSalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbValidarDisponibilidad, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                    .addComponent(jbBajar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbSubir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jcMostrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbSubir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbBajar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbValidarDisponibilidad)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jcMostrar))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jcEstados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jbAsignar))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jbSalir)
                        .addComponent(jLabel2)
                        .addComponent(jtCantidadCargas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3)
                        .addComponent(jtPesoTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbSubirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSubirActionPerformed
        JDSubirCarga win = new JDSubirCarga(this, true, camion);
        win.setVisible(true);
    }//GEN-LAST:event_jbSubirActionPerformed

    private void jbSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_jbSalirActionPerformed

    private void jcMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcMostrarActionPerformed
        llenarTabla(camion.getListadoCargas());
        jtCantidadCargas.setText(String.valueOf(camion.totalCargas()));
        jtPesoTotal.setText(String.valueOf(camion.calcularPeso()));
    }//GEN-LAST:event_jcMostrarActionPerformed

    private void jbBajarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBajarActionPerformed
        int fila = jtCargas.getSelectedRow();
        Carga c = null;
        if (fila != -1) {
            //Si es bidon
            if (!jtCargas.getValueAt(fila, 2).equals("")) {
                c = new Bidon(jtCargas.getValueAt(fila, 0).toString(),
                        Float.parseFloat(jtCargas.getValueAt(fila, 2).toString()),
                        Float.parseFloat(jtCargas.getValueAt(fila, 3).toString()));
            } else if (jtCargas.getValueAt(fila, 4).equals("")==false) {
                c = new Packing(jtCargas.getValueAt(fila, 0).toString(),
                        Float.parseFloat(jtCargas.getValueAt(fila, 5).toString()),
                        Integer.parseInt(jtCargas.getValueAt(fila, 4).toString()),
                        Float.parseFloat(jtCargas.getValueAt(fila, 6).toString()));
            } else {
                c = new Caja(jtCargas.getValueAt(fila, 0).toString(), Float.parseFloat(jtCargas.getValueAt(fila, 1).toString()));
            }
            camion.bajar(c);
            JOptionPane.showMessageDialog(this, "Carga eliminada");
            jcMostrarActionPerformed(null);
        }

    }//GEN-LAST:event_jbBajarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbAsignar;
    private javax.swing.JButton jbBajar;
    private javax.swing.JButton jbSalir;
    private javax.swing.JButton jbSubir;
    private javax.swing.JButton jbValidarDisponibilidad;
    private javax.swing.JComboBox<String> jcEstados;
    private javax.swing.JButton jcMostrar;
    private javax.swing.JTextField jtCantidadCargas;
    private javax.swing.JTable jtCargas;
    private javax.swing.JTextField jtPesoTotal;
    // End of variables declaration//GEN-END:variables

    private void llenarTabla(ArrayList<Carga> cargas) {
        DefaultTableModel model = new DefaultTableModel();

        model.setColumnIdentifiers(new String[]{"Contenido", "Peso", "Densidad", "Capacidad", "Cantidad Cajas", "Peso x caja", "Peso Estructura"});
        String fila[] = new String[7];
        for (Carga c : cargas) {
            fila[0] = c.getContenido();
            fila[1] = String.valueOf(c.calcularPeso());
            if (c instanceof Packing) {
                Packing packing = (Packing) c;
                fila[2] = "";
                fila[3] = "";
                
                fila[4] = String.valueOf(packing.getCantidad());
                fila[5] = String.valueOf(packing.getPesoCaja());
                fila[6] = String.valueOf(packing.getPesoEstructura());
            } else if (c instanceof Bidon) {
                Bidon bidon = (Bidon) c;
                fila[2] = String.valueOf(bidon.getCapacidad());
                fila[3] = String.valueOf(bidon.getDensidad());;
                fila[4] = "";
                fila[5] = "";
                fila[6] = "";
            } else {
                fila[2] = "";
                fila[3] = "";
                fila[4] = "";
                fila[5] = "";
                fila[6] = "";
            }

            model.addRow(fila);
        }
        jtCargas.setModel(model);
    }
}
