/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ejemplo.gui;

import com.ejemplo.dominio.Biblioteca;
import com.ejemplo.dominio.Libro;
import com.ejemplo.dominio.Publicacion;
import com.ejemplo.dominio.Revista;
import java.text.ParseException;
import javax.swing.JOptionPane;

/**
 *
 * @author MARTIN
 */
public class JDNuevaPublicacion extends javax.swing.JDialog {

    /**
     * Creates new form JDNuevoObjeto
     */
    private Biblioteca biblioteca;
    
    public JDNuevaPublicacion(java.awt.Frame parent, boolean modal, Biblioteca biblio) {
        super(parent, modal);
        initComponents();
        this.biblioteca = biblio;
  
        jcbTipos.setSelectedIndex(0);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jcbTipos = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jtTitulo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jtPaginas = new javax.swing.JTextField();
        jtCampo1 = new javax.swing.JTextField();
        jlCampo1 = new javax.swing.JLabel();
        lblExtra1 = new javax.swing.JLabel();
        jtCampo2 = new javax.swing.JTextField();
        jlbExtra2 = new javax.swing.JLabel();
        jtCampo3 = new javax.swing.JTextField();
        jbAceptar = new javax.swing.JButton();
        jbCancelar = new javax.swing.JButton();
        jlCampo2 = new javax.swing.JLabel();
        jlCampo3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Agregar nueva publicación");
        setResizable(false);

        jLabel3.setText("Tipo:");

        jcbTipos.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1- Libro", "2- Revista" }));
        jcbTipos.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcbTiposItemStateChanged(evt);
            }
        });
        jcbTipos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbTiposActionPerformed(evt);
            }
        });

        jLabel1.setText("Título:");

        jLabel2.setText("Páginas:");

        jtPaginas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtPaginasActionPerformed(evt);
            }
        });
        jtPaginas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtPaginasKeyTyped(evt);
            }
        });

        jtCampo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtCampo1ActionPerformed(evt);
            }
        });

        jlCampo1.setText("jLabel1");

        jtCampo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtCampo2ActionPerformed(evt);
            }
        });

        jtCampo3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtCampo3ActionPerformed(evt);
            }
        });

        jbAceptar.setText("Aceptar");
        jbAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAceptarActionPerformed(evt);
            }
        });

        jbCancelar.setText("Cancelar");
        jbCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCancelarActionPerformed(evt);
            }
        });

        jlCampo2.setText("jLabel2");

        jlCampo3.setText("JLabel3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jlCampo1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jlCampo2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jlCampo3, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbAceptar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbCancelar))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jtCampo2)
                        .addComponent(jtCampo1)
                        .addComponent(jtTitulo)
                        .addComponent(jcbTipos, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jtCampo3)
                        .addComponent(jtPaginas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jlbExtra2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblExtra1)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(lblExtra1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlbExtra2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jcbTipos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtPaginas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtCampo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlCampo1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtCampo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlCampo2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtCampo3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlCampo3))))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbAceptar)
                    .addComponent(jbCancelar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jcbTiposItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcbTiposItemStateChanged

    }//GEN-LAST:event_jcbTiposItemStateChanged

    private void jcbTiposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbTiposActionPerformed
        if (jcbTipos.getSelectedIndex() != -1) {
            char t = jcbTipos.getSelectedItem().toString().charAt(0);
            if (t == '1') {
                jlCampo1.setText("ISBN:");
                jlCampo2.setText("Autor:");
                jlCampo3.setVisible(false);
                jtCampo3.setVisible(false);
                jlCampo2.setVisible(true);
                jtCampo2.setVisible(true);
                jlCampo1.setVisible(true);
                jtCampo1.setVisible(true);
                
            } else {
                jlCampo3.setText("Código:");
                jlCampo3.setVisible(true);
                jtCampo3.setVisible(true);
                jlCampo2.setVisible(false);
                jtCampo2.setVisible(false);
                jlCampo1.setVisible(false);
                jtCampo1.setVisible(false);
            }
        }
    }//GEN-LAST:event_jcbTiposActionPerformed

    private void jtPaginasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtPaginasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtPaginasActionPerformed

    private void jtCampo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtCampo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtCampo1ActionPerformed

    private void jtCampo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtCampo2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtCampo2ActionPerformed

    private void jtCampo3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtCampo3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtCampo3ActionPerformed

    private void jbAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAceptarActionPerformed
        String tit;
        int paginas, cod;
        Publicacion ejemplar;
        try {
            paginas = Integer.parseInt(jtPaginas.getText());
            tit = jtTitulo.getText();
            
            if (jcbTipos.getSelectedItem().toString().charAt(0) == '1') {
                ejemplar = new Libro(jtCampo1.getText(),jtCampo2.getText(), tit, paginas);
            } else {
                cod = Integer.parseInt(jtCampo3.getText());
                ejemplar = new Revista(cod, tit, paginas);
            }
            boolean aviso = biblioteca.agregarPublicacion(ejemplar);
            if(aviso)
                JOptionPane.showMessageDialog(this, "Ejemplar registrado!");
            else
                JOptionPane.showMessageDialog(this, "NO se ha podido registrar el ejemplar!");
            
            this.dispose();
        } catch (NumberFormatException nfe) {
            JOptionPane.showMessageDialog(this, "Error de números");
        }
    }//GEN-LAST:event_jbAceptarActionPerformed

    private void jbCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_jbCancelarActionPerformed

    private void jtPaginasKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtPaginasKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jtPaginasKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton jbAceptar;
    private javax.swing.JButton jbCancelar;
    private javax.swing.JComboBox jcbTipos;
    private javax.swing.JLabel jlCampo1;
    private javax.swing.JLabel jlCampo2;
    private javax.swing.JLabel jlCampo3;
    private javax.swing.JLabel jlbExtra2;
    private javax.swing.JTextField jtCampo1;
    private javax.swing.JTextField jtCampo2;
    private javax.swing.JTextField jtCampo3;
    private javax.swing.JTextField jtPaginas;
    private javax.swing.JTextField jtTitulo;
    private javax.swing.JLabel lblExtra1;
    // End of variables declaration//GEN-END:variables
}
